apiVersion: v1alpha
kind: playwright
sauce:
  region: eu-central-1
  concurrency: 1
playwright:
  version: 1.60.0
suites:
  - name: Platnest Smoke Tests
    platformName: Windows 11
    testMatch:
      - "tests/auth/test_register.py"
    params:
      browserName: chromium
    env:
      APP_USERNAME: rajatsharan05@gmail.com
      APP_PASSWORD: Admin@123
      BASE_URL: http://platnest.test
reporters:
  spotlight:
    enabled: true